[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
memoize = "0.4.2"
regex = "1.11.1"
pathfinding = "4.12.0"
itertools = "0.13.0"
